[project]
site_name = "Hamster Hunter Wiki"
site_dir = "dist"
docs_dir = "pages"
site_url = "hh.github.aspy.dev"

[project.theme]
logo = "/assets/logo.png"
favicon = "/assets/logo.png"
features = [
    "search.highlight"
]

[project.theme.palette]
scheme = "slate"

[project.markdown_extensions.zensical.extensions.macros]
module_name = "macros"

[project.markdown_extensions.md_in_html]