name: Publish
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v6
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: true
      - run: uv sync --locked --all-extras --dev
      
      - name: Restore playwright cache
        uses: actions/cache/restore@v5
        with:
          path: |
            ~/.cache/ms-playwright
          key: playwright-cache

      - run: curl -fsSL https://d2lang.com/install.sh | sh -s --

      - name: Cache playwright binaries
        uses: actions/cache/save@v5
        with:
          path: ~/.cache/ms-playwright
          key: playwright-cache

      - name: Generate diagram
        run: d2 recipes.d2 pages/assets/recipes.png

      - run: uv run zensical build --clean 
      - uses: actions/upload-pages-artifact@v5
        with:
          path: dist
      - uses: actions/deploy-pages@v5
        id: deployment